image: privacybydesign/ruby:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
  - vendor/ruby

stages:
  - build

before_script:
  - set -euxo pipefail
  - gem install bundler -v "~>1.0"
  - bundle install --path vendor

site:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - _site/*
  script:
    - bundle exec jekyll build --config _config.yml
